### ISSUE TITLE
Icon does not refresh after Revert

### ISSUE THREAD

**Issue by michaelclockstone** [NibbleByte/UnityWiseSVN#2]
The exclamation mark icon is not removed immeditely after a revert command.

**Comment by NibbleByte** [comment]
This happens only when the asset has a lock or remote changes. Another way is if you are reverting too many files in one go (at the moment that means 10) - the post processor will just do a full icons refresh instead of checking assets individually (optimization).

In my last commit eda8505 I've improved this logic - icons should refresh instantly even with locks or remote changes.

Expect this fix in the next release of WiseSVN as well, which should be this week if all goes well. Will close the issue after the release.
